# Configuration file for a machine learning project
batchSize: 32
imgHeight: 180
imgWidth: 180
epochs: 10

# Paths to datasets
trainDatasetPath: "data/train"

# Paths to save model
modelPath: "data/model/model.keras"

# Server configuration
port: 5001

# Model parameters
modelName: "MobileNetV3Large"